### PR TITLE
Check response before using it

### PR DESCRIPTION
**Pull request by EasyAsABC123**

### CODE REVIEW

**Comment by Jaid** [comment]
Do we really have to check if `response` is falsy in `shouldRetryRequest`? Does this mean there are cases where [requestretry](https://www.npmjs.com/package/requestretry) (or [request](https://www.npmjs.com/package/request)) call `shouldRetryRequest` with a falsy `response` argument?

If they do so, shouldn't we check for `(!response)` in `getRetryReason` and return a proper reason? I mean, `response` being falsy looks like a case where we want to retry the request to me.

I may misunderstand something here.

**Comment by Jaid** [comment]
Okay, I took a quick look into the [requestretry source](https://github.com/FGRibreau/node-request-retry/blob/cbe23552fb5aee1886cd8903d64834edc3e71cd5/strategies/HTTPError.js#L9).
The first thing `getRetryReason` does is passing `response` and `error` to `retryrequest.RetryStrategies.HTTPOrNetworkError()`. This function checks if `response` is falsy, so we probably shouldn't add any own checks to that logic.

**Comment by EasyAsABC123** [comment]
It needs some logic for this as currently twitch-helix crashes due to this being null and then being accessed.

I'll post the exception if needed currently I'm running off my fork instead of v1.0.0 as it just crashes.

**Comment by Jaid** [comment]
You seem to be right. I now added a truthy check to `shouldRetryRequest` before calling `this.log()`. Should fix it.

Sorry for the waiting time.

**Pull request closed without merging**
